server:
  port: 8080

spring:
  application:
    name: gateway

  cloud:
    gateway:
      routes:
        - id: personModule
          #uri: http://localhost:8585/
          uri: lb://PERSON-APP/
          predicates:
            - Path=/persona/**,/producto/**,/productByPerson/**

eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    instance:
    preferIpAddress: true